### ISSUE TITLE
Make deprecated write call save

### ISSUE THREAD

**Issue by ManonMarchand** [cds-astro/mocpy#114]
The deprecated `write` method does not sort the MOC while the new `save` does. This causes compatibility issues with aladin desktop. Let's fix it for now before removing the deprecated function (likely in v1)

**Comment by fxpineau** [comment]
Fwiw, in general you cannot expect attributes to be ordered in a JSON document, 
see e.g.: https://stackoverflow.com/questions/16870416/does-the-sequence-of-the-values-matter-in-a-json-object

From my point-of-view the problem here comes from the fact that the Java MOC implementation requires `depth` attributes to be sorted. I warn in vain since the very beginning against the possible troubles it would inevitably cause. And here we are...
