### ISSUE TITLE
from_vizier_table returns empty MOC silently on incorrect table names

### ISSUE THREAD

**Issue by lmichel** [cds-astro/mocpy#143]
The following code:

```python
from mocpy import MOC

moc = MOC.from_vizier_table('II/355')
moc.save("II_355.fits", format="fits")

moc = MOC.from_vizier_table('WQAZSXCDE.fits')
moc.save("WQAZSXCDE", format="fits")

moc = MOC.from_vizier_table('II/355/dr3')
moc.save("II_355_dr3.fits", format="fits")
```

Produces the following output files, all with the same size:

```bash
% ls -lrt *.FITS
-rw-rw-r-- 1 laurent.michel laurent.michel  5760 Jun 26 18:29 II_355.fits
-rw-rw-r-- 1 laurent.michel laurent.michel  5760 Jun 26 18:30 WQAZSXCDE.fits
-rw-rw-r-- 1 laurent.michel laurent.michel  5760 Jun 26 18:34 II_355_dr3.fits
```

None if these MOC files contains data.

- The method should improved:
    - Make it working with valid table ids
    - returning something telling the user the table ID is wrong
- Writing in the doc how to get (or what is) a valid table id

**Comment by ManonMarchand** [comment]
I guess you're trying to get `I/355/gaiadr3` ? The valid tables names can be read from VizieR http://vizier.cds.unistra.fr/viz-bin/VizieR?-source=I/355&-to=2

You're right that we should raise a warning (or even an error?) if the result is empty.

**Comment by lmichel** [comment]
As you know, CutPast is our worse friend... 

I rewrote my script:
```python
from mocpy import MOC
for id in ["I/355", "I/355/gaiadr3", "AZERTYUIOP"]:
    moc = MOC.from_vizier_table(id)
    print(moc)

0/
WARNING: Keyword 'TTYPE1' found more than once in a same HDU! We use the first occurrence.
0/0-11 
8/
0/

```

In this example, I've a valid Vizier catalogue ID (I/355), a valid Vizier table ID (I/355/gaiadr3) and an invalid ID.

However, none of those return any valid MOC
- Did I do something wrong?
- I also noticed that the first one (I/355), supposed to be valid, raises a FITS warning

My expectations:
- get a valid MOC for I/355
- have something telling me that this MOC has been properly generated whereas that other one not and why (the function might return a tuple or raise an exception).

**Comment by ManonMarchand** [comment]
These are all valid MOCs.

- the first and last ones are empty (`0/`)
- the second one is the result you asked for. See later for detailed explanation

## On empty MOCs

Yes, we plan to raise a warning (or error, not decided yet) for empty MOCs in future versions.

## On the expected result 

The only correct entry here is `I/355/gaiadr3` as it is a VizieR **table** (not catalog, see the method's name):

```python
from mocpy import MOC
moc = MOC.from_vizier_table("I/355/gaiadr3")
print(moc)
```

```
0/0-11 
8/
```

is the expected result. You did not specify the order. The default is 8 so you get a MOC with a max order of 8 (`8/`). As the survey covers the whole sky, it has all the cells at order 0 (`0/0-11`).

If you want a whole catalog, an undocumented trick is to do 

```python
from mocpy import MOC
moc = MOC.from_vizier_table("I/355/*")
print(moc)
```
That only works because the default of the MOCServer is to return the union of all the MOCs, and here "I/355/*" would match any gaia table.

## About the warning you got

The warning is upstream. @pferniqu , the FITS file returned by the MOCServer has two `TTYPE1` in its header (one is `TTYPE1  = 'UNIQ    '` and the other is `TTYPE1  = 'NPIX    '`, see this file [CDS_I_355_gaiadr3.zip](https://github.com/user-attachments/files/16032674/CDS_I_355_gaiadr3.zip) that I got from Laurent's request)

**Comment by tboch** [comment]
I support Laurent's request. Giving an invalid VizieR table identifier should return an error, not an empty MOC.
