### ISSUE TITLE
from_table method missed in the last version

### ISSUE THREAD

**Issue by ggreco77** [cds-astro/mocpy#27]
In the last mocpy version  the method **from_table** is supressed. Why?

**Comment by bmatthieu3** [comment]
`from_table` is redundant with from_lonlat(lon<astropy.units.Quantity>, lat <astropy.units.Quantity>) or from_skycoords(coords<astropy.coordinates.SkyCoord>).

Given an astropy.table.Table object you can do the same thing with from_lonlat e.g.:
`new_moc = MOC.from_lonlat(table['_RAJ2000'], table['_DEJ2000'], max_norder=<your MOC resolution order>)`

`from_table` is also faster than the past method doing the same thing (`from_coo_list` if I remember) because it uses operations on numpy arrays.

**Comment by ggreco77** [comment]
Many thanks, I will use  the method **.from_lonlat**
