### ISSUE TITLE
perimeter extraction

### ISSUE THREAD

**Issue by ggreco77** [cds-astro/mocpy#29]
I suggest to build a new function to extract the perimeter of a MOC as in the Aladin Desktop - 
`export -ajs moc.fits`. We can use it in several applications for specific plots.

best,
Giuseppe

**Comment by bmatthieu3** [comment]
Hi @ggreco77,

I need more precision about your needs : 
* Do you want a method that directly plot the perimeter of a MOC ?
* You want a list of all the skycoords delimiting the MOC (no specific order ? (anti-)clockwise order around the MOC ? What about MOCs having holes in them ? multiple MOCs that are not connexe ?).

The first point can be done with matplotlib patches. A pathpatch can be used to plot the perimeter delimiting the MOC regions from the non-MOC regions. But the second point is trickier I would say because of all the cases (holes, multiples MOCs...) that must be handled. The first point is not so tricky because we do not need a particular order for plotting the edges of all the HEALPix cells lying in the border of a MOC - the perimeter can be plotted edge by edge.

Thank you for your answer.

**Comment by ggreco77** [comment]
I prefer the second proposal with  specific matplotlib patches. In fact, at the end of day, we want to plot the MOC perimeter using matplotlib. Most probably we want a set of matplotlib methods 1) plotting  the perimeter increasing the line thickness 2)  filling the area with transparency from 0 to 1  (no MOC grid).

Thanks to take into account this issue.
