### ISSUE TITLE
Create the MOC for a set of FITS images

### ISSUE THREAD

**Issue by tboch** [cds-astro/mocpy#3]
It would be nice if one could create the MOC corresponding to a set of FITS images (having WCS information)

**Comment by bmatthieu3** [comment]
Hi @cdeil . I have pushed a commit on the tmoc branch from mocpy that could do what you want.

There is a basic notebook example in the root of the tmoc branch called MOC_from_fits_file.ipynb .
Could you please test the solution and see if this corresponds to what you want.

Thank you for your feedback

**Comment by cdeil** [comment]
@bmatthieu3 - Thank you very much!

For reference, it's here: https://github.com/cds-astro/mocpy/commit/20b97c5f6bdf4a1bfc6f3e862adcf8551d114c4d

Yes, this looks exactly like the functionality that I need.

I would suggest to expose it via `MOC.from_image` or `MOC.from_mask_image`, instead of kicking off such a computation in `MOC.from_file`.
As a test image, I would suggest you put a mask in `.fits.gz`, instead of bloating the code repo with the 18 MB with the float32 large image `notebooks/demo-data/image_with_mask.fits` that you have at the moment.
I didn't think about your +- 0.5 yet, whether they are correct. Could you add a comment in the docstring of `from_mask_image` what the logic is that you have implemented: is it pixel centers or corners?

**Comment by bmatthieu3** [comment]
Thank you for your response !

I pushed a MOC.from_image as you have suggested. The params are the following :  
- a fits.header for the dimensions
- the order of the MOC to compute (<= 29, the bigger the finest)
- a mask_arr (optional). If none, it computes a MOC covering the full image.

If you have more suggestions to enhance my code, feel free to ask, I am not yet very familiar with fits.

**Comment by bmatthieu3** [comment]
#49 enhances **from_fits_image**. The method takes the hdulist of the FITS image opened with astropy.io.fits. It can also take an optional boolean mask of the same size of the image. If the max depth given corresponds to a angular resolution < to the angular resolution between 2 consecutive pixels you can have a MOC with holes! This PR fixes this problem by degrading the MOC if this is the case. NaN pixel values are also ignored in the resulted MOC.

**Comment by bmatthieu3** [comment]
#49 has been merged and is contained in the release v0.8.1. I close this issue.
