### ISSUE TITLE
IntervalSet Depracated

### ISSUE THREAD

**Issue by mcoughlin** [cds-astro/mocpy#93]
It seems like in the latest version on pypi 0.12.1, from mocpy import IntervalSet seems to now fail. Is there a changelog or transition suggestion documented somewhere?

**Comment by fxpineau** [comment]
@mcoughlin, @lpsinger 

`IntervalSet` has been removed for quite good reasons (from the MOCPy point-of-view) and the overall MOCPy code is more coherent now than it was in the previous releases supporting the MOC v2.0 standard.

@mcoughlin

Let me know which methods of `IntervalSet` you are using so I can help you for the transition
(I think/hope that the MOC class contains all the necessary methods).
 

@lpsinger 

From a quick look at healpix-alchemy, it seems that IntervaSet is only used [here](https://github.com/skyportal/healpix-alchemy/blob/main/healpix_alchemy/constants.py#L7) to get the HPX_MAX_ORDER constant. 
Is it correct?

The value of the constant (29) is not used is the python part of MOCPy, explaining why it has been removed (we do not suspected external usages).

One solution would be to re-declare constants in the MOC and TimeMOC classes (adding a comment telling that it is used externally), such as: 
* MOC.MAX_ORDER
* TimeMOC.MAX_ORDER

What do you think?

**Comment by lpsinger** [comment]
> From a quick look at healpix-alchemy, it seems that IntervaSet is only used [here](https://github.com/skyportal/healpix-alchemy/blob/main/healpix_alchemy/constants.py#L7) to get the HPX_MAX_ORDER constant. Is it correct?

No. It's much deeper than that. We have a fundamental dependency on interval sets because that's what we store in the database: the interval set as intervals of nested indices:

https://github.com/skyportal/healpix-alchemy/blob/v1.0.1/healpix_alchemy/types.py#L81

Will that functionality still be available in mocpy?

**Comment by fxpineau** [comment]
I see...
We already have a method [to_ranges](https://github.com/cds-astro/mocpy/blob/66b0b42870d584472cfdf265215f3136408cfbab/src/lib.rs#L1628) on the Rust side that we so far only call inside [TimeMOC](https://github.com/cds-astro/mocpy/blob/6825db4d9d393603aee4aee7b9db977f007fa457/python/mocpy/tmoc/tmoc.py#L96).
It is late here (France) but tomorrow I will make a new release with a `MOC.to_depth29_ranges` method (equivalent to the former `IntervalSet.nested` method (name chosen since we already have a [MOC.from_depth29_ranges](https://github.com/cds-astro/mocpy/blob/66b0b42870d584472cfdf265215f3136408cfbab/python/mocpy/moc/moc.py#L1054) method; doc to be updated to specify that we use the HEALPIx nested scheme).

**Comment by fxpineau** [comment]
@lpsinger , @mcoughlin 

MOCPy v0.12.2 has been published with `MOC.MOC_ORDER` and `MOC.to_depth29_ranges`, see [CHANGELOG](https://github.com/cds-astro/mocpy/blob/master/CHANGELOG.md#0122) for more details.

Let me know is something else is missing/should be improved, else you can close the issue (or I will do it in a few days).

Thank you very much for your messages.

**Comment by fxpineau** [comment]
@mcoughlin 

You can use the method [MOC.flatten()](https://cds-astro.github.io/mocpy/stubs/mocpy.MOC.html#mocpy.MOC.flatten), possibly degrading the MOC at the required depth beforehand with  [MOC.degrade_to_order(new_order)](https://cds-astro.github.io/mocpy/stubs/mocpy.MOC.html#mocpy.MOC.degrade_to_order).

Also,  note that `MOC.from_healpix_cells(ipix, depth, fully_covered)` is replaced by [MOC.from_healpix_cells(ipix, depth, moc_depth)](https://cds-astro.github.io/mocpy/stubs/mocpy.MOC.html#mocpy.MOC.from_healpix_cells) because:
* `fully_covered` was not used internally
* the depth of a MOC may be different from the deepest depth in the input list

**Comment by fxpineau** [comment]
Re-looking at your code, if `elliptical_cone_search` comes from cdshealpix python,
you may simplify it by calling directly [MOC.from_elliptical_cone](https://cds-astro.github.io/mocpy/stubs/mocpy.MOC.html#mocpy.MOC.from_elliptical_cone) instead of `elliptical_cone_search` + `from_healpix_cells`.

**Comment by mcoughlin** [comment]
Perfect thanks @fxpineau!

**Comment by mcoughlin** [comment]
@fxpineau I see some slightly funny behavior with that:

import numpy as np
from mocpy import MOC                                                              
import astropy.units as u                                                          
from astropy.coordinates import Angle, Longitude, Latitude
moc = MOC.from_elliptical_cone(
 lon=Longitude(0 * u.deg),
 lat=Latitude(0 * u.deg),
 a=Angle(10, u.deg),
 b=Angle(5, u.deg),
 pa=Angle(179, u.deg),
 max_depth=10
)

gives:

Traceback (most recent call last):
  File "/Users/mcoughlin/Code/ZTF/skyportal-branches/ha_1p0p2/skyportal/test_moc.py", line 5, in <module>
    moc = MOC.from_elliptical_cone(
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.9/site-packages/mocpy/moc/moc.py", line 819, in from_elliptical_cone
    index = mocpy.from_elliptical_cone(
ValueError: Position angle must be in [0, pi[

Are the units here correct?

**Comment by fxpineau** [comment]
@mcoughlin 

It is a bug, because of the wrong constant (PI/2 instead of PI) in the test [here](https://github.com/cds-astro/cds-moc-rust/blob/main/src/storage/u64idx/mod.rs#L953).

Can a new release wait until Monday?

**Comment by mcoughlin** [comment]
@fxpineau yes. Just let me know when it is released please.

**Comment by fxpineau** [comment]
@mcoughlin v0.12.3 released

**Comment by mcoughlin** [comment]
@fxpineau thanks!

**Comment by ManonMarchand** [comment]
Are all the issues solved? @lpsinger did we miss something in your case?
Also, we're sorry for the inconvenience with the API changes. Mocpy got a major improvement in its performances with this release. A lot of things work way better and we're actively developing towards a stable API. If you need anything, now is a really good time to ask for features

**Comment by mcoughlin** [comment]
@ManonMarchand I think capabilities are back to parity. We have been running in production for a bit, and so I think this issue can be closed. @lpsinger should also give his perspective.

**Comment by lpsinger** [comment]
Fine with me.
